<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Library.LearningManagement">
      <HintPath>..\..\App.Canvas\Library.LearningManagement\bin\Debug\net8.0\Library.LearningManagement.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
